---

- hosts: all
  gather_facts: false

  user: ubuntu
  become: true
  become_user: root
  
  roles:
    - python-simplejson # required for ansible
    - hostname
    - unattended-upgrades
    - slack-bots
    - reboot