---

- name: install packages
  apt: 
    pkg: '{{ item }}'
  with_items:
    - python-pip

- name: install python packages
  pip:
    name: '{{ item }}'
    extra_args: --upgrade --no-cache-dir
  with_items:
    - slackclient

- name: install slackin
  npm:
    name: slackin
    global: yes

- name: template rc.local
  template: 
    src: rc.local.j2
    dest: /etc/rc.local
    mode: '755'

- name: template welcomebot.py
  template: 
    src: welcomebot.py.j2
    dest: /usr/local/bin/welcomebot.py
    mode: '755'
