---

- name: install packages
  apt: 
    pkg: '{{ item }}'
  with_items:
    - nginx

- name: open ports 80,443
  ufw:
    rule: allow
    name: Nginx Full

- name: disable default site
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent