---

- hosts: all
  gather_facts: false

  user: ubuntu
  become: true
  become_user: root
  
  roles:
    - install-python-simplejson # required for ansible
    - set-hostname
    - install-unattended-upgrades
    - install-nginx
    - install-slack-bots
    